services:
  web:
    image: ${NGINX_IMAGE:-nginx:1.25-alpine}
    ports:
      - "${NGINX_PORT:-8001}:80"
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      NGINX_HOST: ${NGINX_HOST:-localhost}
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - laravel-development

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - laravel-development

  workspace:
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "${VITE_PORT:-5173}:5173"
    environment:
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}
      VITE_HOST: ${VITE_HOST:-0.0.0.0}
      VITE_HMR_HOST: ${VITE_HMR_HOST:-localhost}
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - laravel-development

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16-alpine}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-laravel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-laravel}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-development

  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    networks:
      - laravel-development

networks:
  laravel-development:

volumes:
  postgres-data-development: